import { Inter } from 'next/font/google';
import './globals.css';
import './css/box_icon.css';
import './css/app.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Blog - Welcome',
  description: 'Web application Generated by Alkaou Dembele.',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{ backgroundColor: "#FFF" }}>
          {children}
        </div>
      </body>
    </html>
  )
}
